DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS authors CASCADE;

CREATE TABLE IF NOT EXISTS authors (
    author_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(512) NOT NULL,
    birth_year integer
);

CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(512) NOT NULL,
    author_id bigint NOT NULL REFERENCES authors (author_id) ON DELETE CASCADE,
    publication_year integer NOT NULL,
    genre varchar(100) NOT NULL
);